Amélioration du code
karimJD/front-end pull request #1
Opened 2022-07-12 13:53 UTC by karimJD

## Description
Le but est d'améliorer la qualité du code.

2022-07-12 14:02 UTC, Jessy-BAER commented on src/app/App.tsx
> +              {/* Avoiding Login, this will be deleted later */}
Il faut remettre le login en place

2022-07-12 14:02 UTC, Jessy-BAER commented on src/app/App.tsx
> -                  // <AuthenticatedRouteGuard>
Il faut garder le guard

2022-07-12 14:05 UTC, Jessy-BAER requested changes

2022-07-12 14:05 UTC, Jessy-BAER commented on src/app/movie/MovieBanner.tsx
> +  }: Movie = movie!;
Je ne comprends pas cette logique

2022-07-12 14:05 UTC, Jessy-BAER commented on src/app/movie/MovieBanner.tsx
> +              {isLoadingPage ? 'loading...' : dayjs(releaseDate).format('YYYY')}
Quand il y a un chargement, on se retrouve avec 'loading...' à plusieurs endroit sur l'écran ? C'est pas bien

2022-07-12 14:05 UTC, Jessy-BAER commented on src/app/movie/categories.service.ts
> +let token = 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTY1NzY5ODA3M30.6ElMnGYshdIEt2gooPakXY9To2_vA0GRm_DckG87oiRfRuaZTRy-xv43ge_xJmtN9KQnIFGGwS
Il y a pas de raison de gerer un token pour contacter l'api, l'intercepteur axios s'en occupe déjà

2022-07-14 06:51 UTC, karimJD commented on src/app/movie/MovieBanner.tsx
> +      ? movies?.[movies?.length - 1]
a la lancement de l'application, la banniere prend le dernier film par defaut et affiche une indication ' latest '. 
je peux l'enlever ou la modifier

2022-07-20 06:45 UTC, closed without merging